import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  breadcrumb,
}: Readonly<{
  children: React.ReactNode;
  breadcrumb: React.ReactNode;
}>) {
  const rng = Math.random();
  return (
    <html lang="en">
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } antialiased ${ geistSans.className }`}
      >
        <nav className="h-16 border flex flex-row gap-2 items-center px-4 relative font-mono">
          <Link href="/"  className="text-3xl w-6 h-6 p-0 border-none">
            <svg
              viewBox="0 0 76 65"
              fill="none" xmlns="http://www.w3.org/2000/svg"><path
                d="M37.5274 0L75.0548 65H0L37.5274 0Z" fill="#000" /></svg>
          </Link>
          {breadcrumb}
          <div className="absolute bottom-0 left-1 text-xs opacity-20 font-mono">layout.tsx {rng}</div>
        </nav>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  );
}


